#
# Makefile -- Friedmann specific stuff to build
#
# (c) 2016 Prof Dr Andreas Mueller, Hochschule Rapperswil
#
.PHONY:	all images clean

all:

images:
	cd images; make images

clean:
	cd images; make clean
