#
# Makefile -- Numerik-Beispiele
#
# (c) 2016 Prof Dr Andreas Mueller, Hochschule Rapperswil
#

dgl:	dgl.c 
	gcc -o dgl -Wall -g -O2 -std=c99 dgl.c -lgsl

rw:	rw.c 
	gcc -o rw -Wall -g -O2 -std=c99 rw.c -lgsl

newton:	newton.c
	gcc -o newton -Wall -g -O2 -std=c99 newton.c 
