#
# Makefile -- build the chapters for the 
#
# (c) 2015 Prof Dr Andreas Mueller, Hochschule Rapperswil
#
.PHONY:	all images clean

all:

images:
	cd images && make images

clean:
	cd images && make clean
